### ISSUE TITLE
K2_2.6.9 not installing in Joomla 3.4.0

### ISSUE THREAD

**Issue by LunaBawa** [joomlaworks/k2-v3-dev-build#212]
The installation wouldnt go through....any solution to this fix
![k2_install_screenshot](https://cloud.githubusercontent.com/assets/11213175/6413849/98ad1da0-be93-11e4-9f5f-f96d9cb998b7.jpg)

**Comment by kavadas** [comment]
You have probably had a previous version of K2 which didn't not uninstall properly. Try this:

1. Uninstall K2.
2. Ensure that is uninstalled correctly. There should be no folder "com_k2" under "components" and "administrator/components" directories. 
3. If those folders exist after you uninstall K2 then this means that something is wrong with your server setup. You need to fix this otherwise you will get the same behavior again and again.

**Comment by LunaBawa** [comment]
Thanks for your response...it worked..
