### ISSUE TITLE
WordLimit for IntroText removes HTML tags

### ISSUE THREAD

**Issue by paulvanharen** [joomlaworks/k2-v3-dev-build#278]
All HTML tags are removed by the WordLimit function for the front-end. This removes the possibility to style the content.

**Comment by fevangelou** [comment]
If we don't remove tags, then some tag may be left open and thus break your entire site. If you switch off WordLimit, styling is kept intact. I would advise you either limit the output with CSS (word wrap ellipsis if I recall properly), or enforce your own styling for the few words passing through the filter.

**Comment by paulvanharen** [comment]
Dear @fevangelou,

There are more solutions to that puzzle. It requires just a simple parser. The rewrite mentioned in the pull request above demonstrates that. 

I created this ticket to have a place holder for the reason to change the code. I ran into that, I implemented the fix, but needed a reference to document the commit.

Best regards, Paul

**Comment by fevangelou** [comment]
The safest solution is to strip everything. This stems from experience &
plain logic.

This code also assumes everything is perfect. What if you have multiple
nested HTML tags (not a few b's or spans) and the actual word limit is
reached and your HTML tags close after another 100 words?

**Comment by paulvanharen** [comment]
I interpret your remark as a call for robustness. I agree with you completely.

Your comments on nested HTML is completely valid and I thought of that as well. Therefore, I decided to leave all tags in unaltered, and to suppress all content between the tags as soon as the word count is reached. It therefore leaves all the HTML structure in place, not touching it. Thus, as long as the input HTML is well formed, the output of the parser is well formed as well. In case one loads additional elements through CSS on those HTML elements, now empty, I would call that the limit of this implementation.

One remark: I took the liberty to strip any comments from the HTML. One has to handle comment tags as well, as HTML comments may be used to hide HTML tags.

**Comment by fevangelou** [comment]
And as you know, well formed HTML by plain authors is a sci-fi tale
unfortunately...

So it's best to stick with what we have but perhaps offer a way to override
default behaviour programmatically when it makes sense aka when you got
educated authors.

Sounds good?

**Comment by paulvanharen** [comment]
I know about the sci-fi tales. Therefore the implementation is not relying on well formed HTML at the start. 

The statement I wanted to make is that the proposed implementation doesn't change the HTML structure. It only eats away the plain text once the word count limit has been reached. That's all. Thus, in case the input is well formed, the output will be as well. And consequently, in case the input is poor, the output will be just as poor. 

Anyway, I think we are spending too much time on this topic. In case you make the call to strip all the HTML tags in word-limit restricted lists, I'm fine with that. Just decide that by choice! It's your call anyway. 

BTW: did you receive my mails on the other 48 tickets? I had some conversation with Krikor on those and I got from him, that there were some issues receiving these mails?

**Comment by creativeprogramming** [comment]
Sorry if I comment on a closed issue, but as I reasoned on feasibility for this 'feature' too in the past I want to give you my 2 cents:

@paulvanharen 
> The statement I wanted to make is that the proposed implementation doesn't change the HTML structure. It only eats away the plain text once the word count limit has been reached

This is a nice solution but there can be more drawbacks than:

> In case one loads additional elements through CSS on those HTML elements, now empty, I would call that the limit of this implementation.

It's not just "more CSS load" there can be layout issues: some html tags in facts can inherith css rules that can have not nice effects on the visual rendering (blank space due to margin, paddings, clear:both etc... and some nasty side effects with float:left/right, and what about <img> a self closing tag?)

Just imagine the following as possible result for one itemlist element:

```html 
<p>This is the limited introtext <h2>With a gaint title</h2> <img src='...' style='float:left;'> text truncated here for instance...
<br/>
<p>
</p>
<hr/>
<img src...>
<h3></h3>
<ul>
<li></li>
<li></li>
</ul>
<table>.....</table>
</p>
```
Can figure this rendered in the list view?

Yes you can try to filter those tags, but then it becomes too complex... now  maybe you'll agree that @fevangelou KISS solution is not a lazy one but indeed a smart, reasoned solution to this common but 'harder than expected' issue (in fact nor Google, Facebook or anybody else is doing this in automatically generated text previews)

Is it worth to reasoning about such complex issue? What's the added benefit? If the target is to allow to have <b><em> and <i> in the introtext preview then maybe you can keep your current parser but use it in combo with a `strip_tags(...,$allowed_tags)` before it, then it can be nice, anyway another issue is that using so much string concatenation/checking is not nice for TTFB  (they have computational costs, any nanosecond is precious as Joomla is already pretty resource hungry in that)

Best Regards
